In [43]:
import pandas as pd
import numpy as np

In [44]:
df=pd.read_csv("/content/iris.csv")

In [45]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [46]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [47]:
X = df[["sepal.length",	"sepal.width","petal.length","petal.width"]]
y = df['variety']

In [48]:
from sklearn.preprocessing import StandardScaler
ss= StandardScaler()
scaled_x = ss.fit_transform(X)

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(scaled_x,y)

In [50]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)


0.9473684210526315

In [51]:
from sklearn.decomposition import PCA
pcam=PCA(n_components=3)
x_pca=pcam.fit_transform(scaled_x)

print("Eigen Vectors =\n",pcam.components_)
print("\nEigen Values =\n",pcam.explained_variance_)

Eigen Vectors =
 [[ 0.52106591 -0.26934744  0.5804131   0.56485654]
 [ 0.37741762  0.92329566  0.02449161  0.06694199]
 [-0.71956635  0.24438178  0.14212637  0.63427274]]

Eigen Values =
 [2.93808505 0.9201649  0.14774182]


In [52]:
print(x_pca)

[[-2.26470281  0.4800266  -0.12770602]
 [-2.08096115 -0.67413356 -0.23460885]
 [-2.36422905 -0.34190802  0.04420148]
 [-2.29938422 -0.59739451  0.09129011]
 [-2.38984217  0.64683538  0.0157382 ]
 [-2.07563095  1.48917752  0.02696829]
 [-2.44402884  0.0476442   0.3354704 ]
 [-2.23284716  0.22314807 -0.0886955 ]
 [-2.33464048 -1.11532768  0.14507686]
 [-2.18432817 -0.46901356 -0.25376557]
 [-2.1663101   1.04369065 -0.2686811 ]
 [-2.32613087  0.13307834  0.09375924]
 [-2.2184509  -0.72867617 -0.23091124]
 [-2.6331007  -0.96150673  0.18079608]
 [-2.1987406   1.86005711 -0.472901  ]
 [-2.26221453  2.68628449  0.03052661]
 [-2.2075877   1.48360936 -0.00534409]
 [-2.19034951  0.48883832 -0.04421532]
 [-1.898572    1.40501879 -0.37434327]
 [-2.34336905  1.12784938  0.13263047]
 [-1.914323    0.40885571 -0.42129259]
 [-2.20701284  0.92412143  0.15986528]
 [-2.7743447   0.45834367  0.3321791 ]
 [-1.81866953  0.08555853  0.0344886 ]
 [-2.22716331  0.13725446  0.11799354]
 [-1.95184633 -0.62561859

In [53]:
from sklearn.model_selection import train_test_split
x_pca_train,x_pca_test, y_train, y_test = train_test_split(x_pca,y)

In [54]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_pca_train,y_train)
model.score(x_pca_test,y_test)

0.9736842105263158